import 'package:flutter/material.dart';
import 'services/api_service.dart';
import 'models/post_model.dart';

void main() {
  runApp(MyApp());
  }

  class MyApp extends StatelessWidget {
    @override
      Widget build(BuildContext context) {
          return MaterialApp(
                home: HomeScreen(),
                    );
                      }
                      }

                      class HomeScreen extends StatefulWidget {
                        @override
                          _HomeScreenState createState() => _HomeScreenState();
                          }

                          class _HomeScreenState extends State<HomeScreen> {
                            final ApiService apiService = ApiService();
                              List<Post> posts = [];
                                Post newPost = Post(id: 0, userId: 0, title: '', body: '');

                                  @override
                                    void initState() {
                                        super.initState();
                                            _fetchPosts();
                                              }

                                                Future<void> _fetchPosts() async {
                                                    final fetchedPosts = await apiService.getPosts();
                                                        setState(() {
                                                              posts = fetchedPosts;
                                                                  });
                                                                    }

                                                                      @override
                                                                        Widget build(BuildContext context) {
                                                                            return Scaffold(
                                                                                  appBar: AppBar(
                                                                                          title: Text('API Example'),
                                                                                                ),
                                                                                                      body: RefreshIndicator(
                                                                                                              onRefresh: _fetchPosts,
                                                                                                                      child: Padding(
                                                                                                                                padding: const EdgeInsets.all(16.0),
                                                                                                                                          child: Column(
                                                                                                                                                      children: [
                                                                                                                                                                    Expanded(
                                                                                                                                                                                    child: ListView.builder(
                                                                                                                                                                                                      itemCount: posts.length,
                                                                                                                                                                                                                        itemBuilder: (context, index) {
                                                                                                                                                                                                                                            return ListTile(
                                                                                                                                                                                                                                                                  title: Text(posts[index].title),
                                                                                                                                                                                                                                                                                        subtitle: Text(posts[index].body),
                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                          if (newPost.id != 0)
                                                                                                                                                                                                                                                                                                                                                                                          ListTile(
                                                                                                                                                                                                                                                                                                                                                                                                            title: Text(newPost.title),
                                                                                                                                                                                                                                                                                                                                                                                                                              subtitle: Text(newPost.body),
                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                          ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        floatingActionButton: Column(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                mainAxisAlignment: MainAxisAlignment.end,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        children: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  FloatingActionButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onPressed: _fetchPosts,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          child: Icon(Icons.refresh),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              SizedBox(height: 16),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        FloatingActionButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onPressed: () async {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  final createdPost = await apiService.createPost(Post(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  id: 101,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  userId: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  title: 'foo',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  body: 'bar',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              setState(() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              newPost = createdPost;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    child: Icon(Icons.add),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
